name: RevivePlugin
version: '${project.version}'
main: org.baguette.reviveplugin.RevivePlugin
api-version: 1.18
authors: [ wizard-chan ]
description: This is an example of a death/revives plugin.
website: wizard.is.hot
